version: "3.7"

services:

  hubmap-neo4j-stage:
    build: ./stage
    # Build the image with name and tag
    image: hubmap-neo4j-stage:1.0
    hostname: hubmap-neo4j-stage
    container_name: hubmap-neo4j-stage
    # Avoid accidentally creating zombie processes
    init: true
    # Specifying a restart policy to avoid downtime
    restart: always
    ports:
      - "7456:7474"
      - "7659:7687"
    volumes:
      # Mount the neo4j configuration file to container
      - "./stage/neo4j.conf:/usr/src/app/neo4j/conf/neo4j.conf"
      # Mount the neo4j sample database to container
      - "./stage/hubmap.db:/usr/src/app/neo4j/data/databases/hubmap.db"
