version: "3.7"

services:

  hubmap-neo4j-test:
    build: ./test
    # Build the image with name and tag
    image: hubmap-neo4j-test:1.0
    hostname: hubmap-neo4j-test
    container_name: hubmap-neo4j-test
    # By default this `deploy` key only takes effect when deploying to a swarm with docker stack deploy, and is ignored by docker-compose up
    # However, we can use the `--compatibility` flag within `docker-compose --compatibility up`
    # The `--compatibility` flag will attempt to convert deploy keys in docker-compose v3 to their non-Swarm equivalent
    deploy:
      resources:
        limits:
          # Modify this based on the actual VM resource
          memory: 3G
    # Avoid accidentally creating zombie processes
    init: true
    # Specifying a restart policy to avoid downtime
    restart: always
    ports:
      - "7455:7474"
      - "7658:7687"
    volumes:
      # Mount the neo4j configuration file to container
      - "./test/neo4j.conf:/usr/src/app/neo4j/conf/neo4j.conf"
      # Mount the neo4j sample database to container
      - "./test/hubmap.db:/usr/src/app/neo4j/data/databases/hubmap.db"
